name: Deploy al Servidor Ubuntu

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Agregar host SSH a known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Backup de la versión anterior en el servidor
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            if [ -d "/var/www/abastopro" ]; then
              TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
              mv "/var/www/abastopro" "/var/www/abastopro_$TIMESTAMP"
            fi
            mkdir -p "/var/www/abastopro"

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "mandanga/*"
          target: "/var/www/abastopro/"

      - name: Ajustar permisos de archivos en el servidor
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            sudo chown -R www-data:www-data /var/www/abastopro
            sudo chmod -R 755 /var/www/abastopro
            sudo systemctl restart apache2
